import {Renderer,categories,effects} from './renderer.js?v=4';
import {Click,contact,distance,dynamicIntensity,smoothIntensity,zoneFromHands,validZone,clamp} from './gestures.js';
const $=id=>document.getElementById(id),video=$('video'),canvas=$('camera'),ctx=canvas.getContext('2d');
const source=document.createElement('canvas'),src=source.getContext('2d'),finished=document.createElement('canvas'),out=finished.getContext('2d');
let renderer,stream,worker,ready=false,busy=false,running=false,starting=false,epoch=0,raf=0,workerTimer;
let effect='Saturación',dynamic=false,intensity=7,dynamicValue=7.5,target=7.5,transition=null;
let hands=[],trackingZone=null,fixedZone=null,lastDetection=0,lastSent=0,lastVideo=-1,lastRendered=-1,lastTick=0;
let photoPending=false,saving=false,preview=null,previewUntil=0,downloadURL=null,counter=0,audio;
const freshClicks=()=>({Left:new Click(),Right:new Click(),effectLeft:new Click(),effectRight:new Click(),ringLeft:new Click(),ringRight:new Click()});let clicks=freshClicks();
let toastTimer;
function toast(message,duration=2400){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),duration)}
function showCategory(name){document.querySelectorAll('#categories button').forEach(b=>b.setAttribute('aria-pressed',String(b.textContent===name)));$('effects').replaceChildren(...categories[name].map(name=>{const b=document.createElement('button');b.textContent=name;b.setAttribute('aria-pressed',String(name===effect));b.onclick=()=>selectEffect(name);return b}))}
function selectEffect(name){if(!effects.includes(name))throw Error('Efecto no válido');effect=name;$('effect-label').textContent=name;showCategory(Object.keys(categories).find(k=>categories[k].includes(name)))}
for(const name of Object.keys(categories)){const b=document.createElement('button');b.textContent=name;b.onclick=()=>showCategory(name);$('categories').append(b)}showCategory('Básicos');
function setMode(value){dynamic=value;$('intensity').disabled=value;$('mode').setAttribute('aria-pressed',String(value));$('mode').textContent=value?'Usar fija':'Usar dinámica';$('mode-label').textContent=value?'DINÁMICA':'FIJA';$('dynamic-hint').hidden=!value;transition=value?{from:intensity,at:performance.now()}:null}
$('mode').onclick=()=>setMode(!dynamic);$('intensity').oninput=e=>{intensity=Number(e.target.value);$('value').value=intensity.toFixed(1)};
function updateZoneUI(){$('locked').hidden=!fixedZone;$('freeze').textContent=fixedZone?'Liberar zona':'Fijar zona';$('freeze').disabled=!running||(!fixedZone&&!validZone(trackingZone))}
function toggleZone(){if(fixedZone){fixedZone=null;toast('Rectángulo libre')}else if(validZone(trackingZone)){fixedZone=trackingZone.map(p=>({...p}));toast('Rectángulo fijo')}else{toast('Mostrá las dos manos para formar el encuadre.');return false}updateZoneUI();return true}
$('freeze').onclick=toggleZone;
function initAudio(){try{audio??=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume().catch(()=>{})}catch{}}
function shutter(){try{if(!audio||audio.state!=='running')return;const buffer=audio.createBuffer(1,Math.ceil(audio.sampleRate*.16),audio.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++){const t=i/audio.sampleRate;data[i]=(Math.random()*2-1)*(.6*Math.exp(-t*100)+(t>=.065?.4*Math.exp(-(t-.065)*100):0))}const sound=audio.createBufferSource();sound.buffer=buffer;sound.connect(audio.destination);sound.start()}catch{}}
function requestPhoto(){initAudio();if(!running){toast('Activá la cámara primero.');return false}if(saving||performance.now()<previewUntil)return false;photoPending=true;return true}
$('capture').onclick=requestPhoto;
function savePhoto(){if(saving)return;saving=true;const snap=document.createElement('canvas');snap.width=finished.width;snap.height=finished.height;snap.getContext('2d').drawImage(finished,0,0);const currentEpoch=epoch;
 snap.toBlob(blob=>{saving=false;if(!blob){toast('No se pudo guardar la foto. Intentá de nuevo.');return}if(epoch!==currentEpoch)return;preview=snap;previewUntil=performance.now()+1000;shutter();$('flash').classList.remove('flash');void $('flash').offsetWidth;$('flash').classList.add('flash');const previous=downloadURL;downloadURL=URL.createObjectURL(blob);if(previous)setTimeout(()=>URL.revokeObjectURL(previous),60000);const name=`camera_fx_${new Date().toISOString().replace(/[:.]/g,'-')}_${++counter}.png`;const link=$('download');link.href=downloadURL;link.download=name;link.hidden=false;link.click();toast('Foto lista. Si no se descargó, usá el enlace de abajo.',2400)},'image/png')}
function processHands(data){busy=false;if(!running||performance.now()-data.time>400)return;lastDetection=performance.now();hands=data.landmarks;trackingZone=zoneFromHands(hands);const readings={};for(let i=0;i<hands.length;i++){const label=data.handedness[i]?.[0];if(!label||label.score<.8)continue;const side=label.categoryName;if(side!=='Left'&&side!=='Right')continue;readings[side]=side in readings?null:hands[i]}
 const now=performance.now();let cycle=false;for(const side of ['Left','Right']){const hand=readings[side];const ring=hand?contact(hand,16,source.width,source.height,.3,.5):null;const pinky=hand?contact(hand,20,source.width,source.height,.3,.5):null;const index=hand?contact(hand,8,source.width,source.height,.3,.5):null;const touches=[index,ring,pinky].filter(v=>v===true).length;const exclusive=value=>touches>1?null:value;const event=clicks[side].update(exclusive(pinky),now);if(event){if(side==='Left')toggleZone();else requestPhoto()}if(clicks['ring'+side].update(exclusive(ring),now)){const control=$(side==='Left'?'border':'points');control.checked=!control.checked;toast(`${side==='Left'?'Bordes':'Puntos'} ${control.checked?'activados':'desactivados'}`,900)}const pinch=hand&&hands.length===2?exclusive(index):null;cycle=clicks['effect'+side].update(pinch,now)||cycle}if(cycle){selectEffect(effects[(effects.indexOf(effect)+1)%effects.length]);toast(effect,450)}
 if(hands.length===2)target=dynamicIntensity(distance(hands[0][0],hands[1][0],source.width,source.height)/source.width);$('tracking').textContent=hands.length?`${hands.length} mano${hands.length===1?'':'s'} detectada${hands.length===1?'':'s'}`:'Esperando manos';updateZoneUI()}
function startWorker(currentEpoch){worker=new Worker(new URL('./tracker.js',import.meta.url));worker.onmessage=({data})=>{if(epoch!==currentEpoch)return;if(data.type==='ready'){clearTimeout(workerTimer);ready=true;$('tracking').textContent='Esperando manos'}else if(data.type==='hands')processHands(data);else {console.error('Seguimiento:',data.message);failTracking()}};worker.onerror=event=>{console.error('Worker:',event.message);if(epoch===currentEpoch)failTracking()};workerTimer=setTimeout(()=>{if(epoch===currentEpoch&&!ready)failTracking()},45000);worker.postMessage({type:'init'})}
function failTracking(){stopCamera();toast('No se pudo iniciar el seguimiento de manos. Revisá la conexión y volvé a activar la cámara.',6000)}
async function startCamera(){if(starting||running)return;starting=true;const token=++epoch;initAudio();$('start').disabled=true;$('start').textContent='Abriendo cámara…';
 try{if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia)throw Error('Abrí esta página con HTTPS o desde localhost para usar la cámara.');renderer??=new Renderer();const obtained=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:false});if(epoch!==token){obtained.getTracks().forEach(t=>t.stop());return}stream=obtained;video.srcObject=stream;await video.play();if(epoch!==token)return;
 const scale=Math.min(1,960/video.videoWidth,720/video.videoHeight);const w=Math.round(video.videoWidth*scale),h=Math.round(video.videoHeight*scale);for(const c of [source,finished,canvas]){c.width=w;c.height=h}running=true;ready=false;busy=false;lastSent=0;lastVideo=-1;lastRendered=-1;lastTick=performance.now();clicks=freshClicks();hands=[];trackingZone=null;fixedZone=null;preview=null;previewUntil=0;
 $('welcome').hidden=true;$('stop').hidden=false;$('capture').disabled=false;$('tracking').textContent='Preparando seguimiento…';startWorker(token);raf=requestAnimationFrame(tick);stream.getVideoTracks()[0].addEventListener('ended',()=>{if(running&&epoch===token){stopCamera();toast('La cámara se desconectó. Podés volver a activarla.')}});
 }catch(error){if(epoch===token){stopCamera();const messages={NotAllowedError:'No se habilitó la cámara. Permití el acceso desde el navegador y volvé a intentar.',NotFoundError:'No encontramos una cámara conectada.',NotReadableError:'La cámara está ocupada. Cerrá la aplicación de Python u otra app que la esté usando.'};toast(messages[error.name]||error.message||'No se pudo abrir la cámara.',7000)}}finally{if(epoch===token||!running){starting=false;$('start').disabled=false;$('start').textContent='Activar cámara'}}}
function stopCamera(){epoch++;running=false;starting=false;ready=false;busy=false;cancelAnimationFrame(raf);clearTimeout(workerTimer);worker?.terminate();worker=null;stream?.getTracks().forEach(t=>t.stop());stream=null;video.srcObject=null;hands=[];trackingZone=null;fixedZone=null;photoPending=false;preview=null;previewUntil=0;ctx.clearRect(0,0,canvas.width,canvas.height);$('welcome').hidden=false;$('stop').hidden=true;$('capture').disabled=true;$('tracking').textContent='Cámara apagada';$('start').disabled=false;$('start').textContent='Activar cámara';updateZoneUI()}
$('start').onclick=startCamera;$('stop').onclick=stopCamera;
function tick(now){if(!running)return;const frame=video.getVideoPlaybackQuality?.().totalVideoFrames||Math.floor(video.currentTime*30);if(frame===lastRendered&&!photoPending){raf=requestAnimationFrame(tick);return}lastRendered=frame;const dt=now-lastTick;lastTick=now;try{
 if(video.readyState>=2){src.setTransform(-1,0,0,1,source.width,0);src.drawImage(video,0,0,source.width,source.height);src.setTransform(1,0,0,1,0,0);
 // Detector y render reciben la misma imagen espejada: Left/Right físicos.
 if(ready&&!busy&&now-lastSent>=50&&video.currentTime!==lastVideo){busy=true;lastSent=now;lastVideo=video.currentTime;const token=epoch;createImageBitmap(source).then(bitmap=>{if(!running||epoch!==token){bitmap.close();return}worker.postMessage({type:'frame',bitmap,time:now},[bitmap])}).catch(()=>{if(epoch===token)busy=false})}
 if(now-lastDetection>400){hands=[];trackingZone=null;for(const click of Object.values(clicks))click.update(null,now);if(ready)$('tracking').textContent='Esperando manos';updateZoneUI()}
 dynamicValue=smoothIntensity(dynamicValue,target,dt);if(dynamic){const blend=transition?clamp((now-transition.at)/400,0,1):1;intensity=transition?transition.from+(dynamicValue-transition.from)*blend:dynamicValue;if(blend===1)transition=null;$('intensity').value=intensity;$('value').value=intensity.toFixed(1)}
 const zone=fixedZone??trackingZone;out.drawImage(renderer.render(source,zone,effect,intensity,now),0,0);
 if(zone&&$('border').checked&&effect!=='Pop rojo'){out.strokeStyle='white';out.lineWidth=1;out.beginPath();zone.forEach((p,i)=>i?out.lineTo(p.x*source.width,p.y*source.height):out.moveTo(p.x*source.width,p.y*source.height));out.closePath();out.stroke()}
 if($('points').checked){out.fillStyle='white';for(const hand of hands)for(const i of [4,8,16,20]){out.beginPath();out.arc(hand[i].x*source.width,hand[i].y*source.height,4,0,Math.PI*2);out.fill()}}
 if(photoPending){photoPending=false;savePhoto()}ctx.drawImage(preview&&now<previewUntil?preview:finished,0,0);if(now>=previewUntil)preview=null;
 }
 raf=requestAnimationFrame(tick);
 }catch(error){stopCamera();toast('Se interrumpió el procesamiento. Volvé a activar la cámara.',5000);console.error(error)}}
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else toast('Podés ampliar la vista girando el teléfono.')}catch{toast('No se pudo activar la pantalla completa.')}};
document.addEventListener('keydown',e=>{if(!running||e.repeat||e.target.matches('input,textarea,select,a')||e.target.isContentEditable)return;if(e.code==='Space'||e.key==='Enter'){e.preventDefault();e.stopImmediatePropagation();requestPhoto()}},true);
window.addEventListener('pagehide',()=>{stopCamera();if(downloadURL)URL.revokeObjectURL(downloadURL);audio?.close()});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&running)stopCamera()});
const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort());
if(document.modelContext?.registerTool){for(const tool of [
 {name:'read_camera_settings',description:'Leer el efecto, intensidad y estado de la zona.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({effect,intensity,dynamic,zoneFixed:!!fixedZone,cameraOn:running})},
 {name:'configure_camera_effect',description:'Elegir efecto e intensidad. No activa la cámara ni toma fotos.',inputSchema:{type:'object',properties:{effect:{type:'string',enum:effects},intensity:{type:'number',minimum:0,maximum:10},dynamic:{type:'boolean'}},required:['effect','intensity','dynamic'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||!effects.includes(input.effect)||typeof input.intensity!=='number'||!Number.isFinite(input.intensity)||input.intensity<0||input.intensity>10||typeof input.dynamic!=='boolean')throw Error('Configuración no válida');selectEffect(input.effect);intensity=input.intensity;setMode(input.dynamic);$('intensity').value=intensity;$('value').value=intensity.toFixed(1);return{effect,intensity,dynamic}}}
 ])try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}}

// Panel replegable para dedicar toda la superficie a la cámara.
function showControls(show){
 $('controls').hidden=!show;
 document.body.classList.toggle('panel-closed',!show);
 $('panel-toggle').setAttribute('aria-expanded',String(show));
 $('panel-toggle').textContent=show?'Ocultar controles':'Mostrar controles';
}
$('panel-toggle').onclick=()=>showControls($('controls').hidden);
showControls(!matchMedia('(max-width: 800px)').matches);
